---
title: "Unsupervised Explore Analysis"
bibliography: references.bib
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(cluster)
library(dplyr)
library(ggplot2)
library(readr)
library(Rtsne)
library(tidyr)
theme_set(theme_bw())

load("Data/Combined_IA_data.Rdata")
```

## Outline
- K-means clustering
- Hierarchical Clustering
- Principal component analysis (PCA)

## k - means Clustering Analysis
```{r kmeans}
#' Compute Gower distance
df_ia_data = 
  as.data.frame(ia_data[,-c(1,2,90)]) %>%
  unnest(dist_private_Elementary:dist_public_Middle) %>%
  mutate_at(vars(starts_with("dist_")), as.numeric) 

i <- grep("dist_", names(df_ia_data))
x <- df_ia_data[, i]
cl <- stats::kmeans(x, 3, nstart = 10)
plot(x, col = cl$cluster)

#testing effectiveness
set.seed(12345)
init <- sample(3, nrow(x), replace = TRUE)
plot(x, col = init)

par(mfrow = c(1, 2))
plot(x, col = init)
centres <- sapply(1:3, function(i) colMeans(x[init == i, ], ))
centres <- t(centres)
points(centres[, 1], centres[, 2], pch = 19, col = 1:3)

tmp <- dist(rbind(centres, x))
tmp <- as.matrix(tmp)[, 1:3]

ki <- apply(tmp, 1, which.min)
ki <- ki[-(1:3)]

plot(x, col = ki)
points(centres[, 1], centres[, 2], pch = 19, col = 1:3)

clusplot(df_ia_data, cl$cluster, main='2D representation of the Cluster solution',
         color=TRUE, shade=TRUE,
         labels=2, lines=0)

#
cl1 <- kmeans(x, centers = 3, nstart = 10)
cl2 <- kmeans(x, centers = 3, nstart = 10)
table(cl1$cluster, cl2$cluster)
```

## Hierarchical clustering
```{r}
d <- df_ia_data[,-1]
hcl <- hclust(d)
hcl
```


## Principal component analysis (PCA)
```{r}
pairs(, col = iris[, 5], pch = 19)

```

